// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsWorldAPI.Context;

#nullable disable

namespace SportsWorldAPI.Migrations
{
    [DbContext(typeof(SportsWorldContext))]
    [Migration("20251215131047_ResetDatabaseSeed")]
    partial class ResetDatabaseSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SportsWorldAPI.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<bool>("PurchaseStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "Male",
                            Image = "messi.jpg",
                            Name = "Lionel Messi",
                            Price = 80000000.0,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 2,
                            Gender = "Female",
                            Image = "graham_hansen.jpg",
                            Name = "Caroline Graham Hansen",
                            Price = 50000000.0,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 3,
                            Gender = "Male",
                            Image = "odegaard.jpg",
                            Name = "Martin Ødegaard",
                            Price = 90000000.0,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 4,
                            Gender = "Female",
                            Image = "putellas.jpg",
                            Name = "Alexia Putellas",
                            Price = 60000000.0,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 5,
                            Gender = "Male",
                            Image = "haaland.jpg",
                            Name = "Erling Braut Haaland",
                            Price = 150000000.0,
                            PurchaseStatus = true
                        },
                        new
                        {
                            Id = 6,
                            Gender = "Female",
                            Image = "aitana.jpg",
                            Name = "Aitana Bonmati",
                            Price = 40000000.0,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 7,
                            Gender = "Male",
                            Image = "modric.jpg",
                            Name = "Luka Modric",
                            Price = 70000000.0,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 8,
                            Gender = "Male",
                            Image = "lewandowski.jpg",
                            Name = "Robert Lewandowski",
                            Price = 80000000.0,
                            PurchaseStatus = true
                        });
                });

            modelBuilder.Entity("SportsWorldAPI.Models.Finance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("MoneyLeft")
                        .HasColumnType("REAL");

                    b.Property<double>("MoneySpent")
                        .HasColumnType("REAL");

                    b.Property<int>("NumberOfPurchases")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Finances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoneyLeft = 640000000.0,
                            MoneySpent = 360000000.0,
                            NumberOfPurchases = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
